config/routes.rb
Rails.application.routes.draw do
  get 'tests/index'
  root 'tests#index'
  get 'contacts/index'
  get 'tweets/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/contacts/index.html.erb
<div data-scope-path="contacts/index">
  <h1>Contacts#index</h1>
  <p>Find me in app/views/contacts/index.html.erb</p>
  <%= link_to 'トップへ', '/'%>
  <h2>スコープ</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breadcrumb2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<div data-scope-path="tweets/index">
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
<%= link_to "コンタクト" , contacts_index_path %>
<h2>更新</h2>
<h3>本当？</h3>
</div>